# Generated by Django 6.0.6 on 2026-06-23 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSecurityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(max_length=256)),
                ('purpose', models.CharField(choices=[('EMAIL_VERIFICATION', 'Email verification'), ('PASSWORD_RESET', 'Password reset')], max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'used_at'], name='accounts_ac_email_8f3086_idx'), models.Index(fields=['user', 'purpose', 'used_at'], name='accounts_ac_user_id_6651e9_idx'), models.Index(fields=['expires_at'], name='accounts_ac_expires_e856e6_idx')],
            },
        ),
    ]
