# Generated by Django 6.0.6 on 2026-06-18 19:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bonds', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('intrinsic_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('iv_to_cost', models.DecimalField(blank=True, decimal_places=6, help_text='Intrinsic value divided by cost.', max_digits=18, null=True)),
                ('iv_vs_market_price', models.DecimalField(blank=True, decimal_places=6, help_text='Intrinsic value minus market price.', max_digits=18, null=True)),
                ('market_price_minus_face_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('current_yield', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('net_ytm', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('approx_aytm', models.DecimalField(blank=True, decimal_places=6, help_text='Approximate annual yield to maturity.', max_digits=12, null=True)),
                ('rcy', models.DecimalField(blank=True, decimal_places=6, help_text='Reinvested coupon yield.', max_digits=12, null=True)),
                ('macaulay_duration', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('modified_duration', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('price_impact', models.DecimalField(blank=True, decimal_places=6, help_text='Estimated price impact based on expected yield change.', max_digits=18, null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('risk_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('100.0000'))])),
                ('risk_level', models.CharField(choices=[('VERY_LOW', 'Very Low'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], default='MEDIUM', max_length=20)),
                ('position_value', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('final_signal', models.CharField(choices=[('BUY', 'Αγορά'), ('BUY_WITH_CAUTION', 'Αγορά με προσοχή'), ('DO_NOT_BUY_WAIT', 'Μη αγορά / Περίμενε'), ('HOLD', 'Διακράτηση'), ('SELL', 'Πώληση'), ('PARTIAL_SELL', 'Μερική πώληση'), ('BUY_MORE', 'Αγορά επιπλέον'), ('REVIEW', 'Επανεξέταση')], default='REVIEW', max_length=30)),
                ('reasoning', models.TextField(blank=True, help_text='Short explanation for the final analytical signal.')),
                ('risk_reasoning', models.TextField(blank=True, help_text='Short explanation for the risk level.')),
                ('calculation_notes', models.TextField(blank=True, help_text='Internal notes about missing data or calculation limits.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='bonds.bondmarketdata')),
                ('user_bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='portfolios.userbond')),
            ],
            options={
                'verbose_name': 'Bond Analysis',
                'verbose_name_plural': 'Bond Analyses',
                'ordering': ['-analysis_date', '-created_at'],
                'unique_together': {('user_bond', 'analysis_date')},
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField()),
                ('payment_date', models.DateField()),
                ('coupon_gross', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('coupon_tax', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('coupon_net', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('principal', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('total_cash_flow', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('discounted_cash_flow', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='analytics.bondanalysis')),
            ],
            options={
                'verbose_name': 'Cash Flow',
                'verbose_name_plural': 'Cash Flows',
                'ordering': ['period_number'],
                'unique_together': {('analysis', 'period_number')},
            },
        ),
    ]
