# Generated by Django 6.0.6 on 2026-06-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondanalysis',
            name='final_signal',
            field=models.CharField(choices=[('BUY', 'Αγορά'), ('BUY_WITH_CAUTION', 'Αγορά με προσοχή'), ('BUY_LOW_YIELD', 'Αγορά αλλά με χαμηλή απόδοση'), ('DO_NOT_BUY_WAIT', 'Μη αγορά / Περίμενε'), ('HOLD', 'Διακράτηση'), ('SELL', 'Πώληση'), ('PARTIAL_SELL', 'Μερική πώληση'), ('BUY_MORE', 'Αγορά επιπλέον'), ('REVIEW', 'Επανεξέταση')], default='REVIEW', max_length=30),
        ),
    ]
