# Generated by Django 6.0.6 on 2026-06-18 19:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bond name as displayed to the user.', max_length=255)),
                ('isin', models.CharField(db_index=True, help_text='International Securities Identification Number.', max_length=20, unique=True)),
                ('issuer', models.CharField(help_text='Bond issuer name.', max_length=255)),
                ('bond_type', models.CharField(choices=[('GOVERNMENT', 'Government Bond'), ('CORPORATE', 'Corporate Bond'), ('TREASURY', 'Treasury'), ('MUNICIPAL', 'Municipal Bond'), ('OTHER', 'Other')], default='GOVERNMENT', max_length=30)),
                ('currency', models.CharField(default='EUR', help_text='Trading currency, for example EUR or USD.', max_length=3)),
                ('seniority', models.CharField(choices=[('SENIOR_SECURED', 'Senior Secured'), ('SENIOR_UNSECURED', 'Senior Unsecured'), ('SUBORDINATED', 'Subordinated'), ('JUNIOR', 'Junior'), ('OTHER', 'Other')], default='SENIOR_UNSECURED', max_length=30)),
                ('is_callable', models.BooleanField(default=False, help_text='Indicates whether the issuer may call the bond early.')),
                ('market_liquidity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('credit_rating', models.CharField(blank=True, help_text='Credit rating, for example AAA, BBB, BB+, etc.', max_length=20)),
                ('face_value', models.DecimalField(decimal_places=4, help_text='Face value per bond.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('annual_coupon_rate', models.DecimalField(decimal_places=4, help_text='Annual coupon rate as a percentage, for example 4.125.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('100.0000'))])),
                ('coupon_frequency', models.PositiveSmallIntegerField(default=1, help_text='Number of coupon payments per year.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('maturity_date', models.DateField(help_text='Bond maturity date.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bond',
                'verbose_name_plural': 'Bonds',
                'ordering': ['isin'],
            },
        ),
        migrations.CreateModel(
            name='BondMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='Date of the market quote.')),
                ('market_price', models.DecimalField(decimal_places=4, help_text='Market price per bond.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('market_required_return', models.DecimalField(blank=True, decimal_places=5, help_text='Market discount rate used for valuation. Stored as percentage, for example 4.25.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-100.00000')), django.core.validators.MaxValueValidator(Decimal('100.00000'))])),
                ('ytm', models.DecimalField(blank=True, decimal_places=5, help_text='Yield to maturity as percentage, if available.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-100.00000')), django.core.validators.MaxValueValidator(Decimal('100.00000'))])),
                ('bid_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('ask_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('source', models.CharField(default='manual', help_text='Data source, for example manual, provider name, or API.', max_length=100)),
                ('is_manual', models.BooleanField(default=True, help_text='True when data was entered manually.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='bonds.bond')),
            ],
            options={
                'verbose_name': 'Bond Market Data',
                'verbose_name_plural': 'Bond Market Data',
                'ordering': ['-quote_date', '-created_at'],
                'unique_together': {('bond', 'quote_date', 'source')},
            },
        ),
    ]
