# Generated by Django 6.0.6 on 2026-06-20 09:49

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bond',
            options={'ordering': ['isin']},
        ),
        migrations.AlterModelOptions(
            name='bondmarketdata',
            options={'ordering': ['-quote_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='bond',
            name='annual_coupon_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Annual coupon rate as percentage. Example: 4.125 means 4.125%.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('100.0000'))]),
        ),
        migrations.AlterField(
            model_name='bond',
            name='credit_rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bond',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='bond',
            name='face_value',
            field=models.DecimalField(decimal_places=4, default=Decimal('100.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='bond',
            name='is_callable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bond',
            name='isin',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bond',
            name='issuer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bond',
            name='maturity_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bond',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bondmarketdata',
            name='is_manual',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bondmarketdata',
            name='market_price',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AlterField(
            model_name='bondmarketdata',
            name='market_required_return',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Market required return as percentage. Example: 4.35 means 4.35%.', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bondmarketdata',
            name='quote_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='bondmarketdata',
            name='source',
            field=models.CharField(default='manual', max_length=100),
        ),
        migrations.AlterField(
            model_name='bondmarketdata',
            name='ytm',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Yield to maturity as percentage. Used as fallback discount rate.', max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='FXRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(help_text='Currency being converted from. Example: USD.', max_length=3)),
                ('quote_currency', models.CharField(help_text='Currency being converted to. Example: EUR.', max_length=3)),
                ('rate_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('rate', models.DecimalField(decimal_places=8, help_text='Conversion rate. Example: 1 USD = 0.92 EUR, rate = 0.92.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('source', models.CharField(default='manual', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rate_date', 'base_currency', 'quote_currency'],
                'unique_together': {('base_currency', 'quote_currency', 'rate_date', 'source')},
            },
        ),
    ]
