# Generated by Django 6.0.6 on 2026-06-20 14:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_alter_bond_options_alter_bondmarketdata_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='static_provider', help_text='Discovery provider name, for example static_provider or csv_provider.', max_length=100)),
                ('min_rating', models.CharField(default='BBB-', help_text='Minimum accepted credit rating for this run.', max_length=20)),
                ('currencies', models.JSONField(blank=True, default=list, help_text='Optional currency filters used by the discovery run.')),
                ('countries', models.JSONField(blank=True, default=list, help_text='Optional country filters used by the discovery run.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_found', models.PositiveIntegerField(default=0, help_text='Raw candidates returned by the provider.')),
                ('total_saved', models.PositiveIntegerField(default=0, help_text='Candidates saved after validation and filtering.')),
                ('total_skipped', models.PositiveIntegerField(default=0, help_text='Candidates skipped due to validation, filtering, or duplicates.')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_discovery_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discovery Run',
                'verbose_name_plural': 'Discovery Runs',
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BondCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(db_index=True, help_text='International Securities Identification Number.', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, help_text='Issuer country code, for example US or GR.', max_length=2)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('coupon_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Annual coupon rate as percentage. Example: 4.125 means 4.125%.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('100.0000'))])),
                ('maturity_date', models.DateField(db_index=True)),
                ('credit_rating', models.CharField(db_index=True, max_length=20)),
                ('rating_source', models.CharField(blank=True, max_length=100)),
                ('market_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('ytm', models.DecimalField(blank=True, decimal_places=5, help_text='Yield to maturity as percentage.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-100.00000')), django.core.validators.MaxValueValidator(Decimal('100.00000'))])),
                ('duration', models.DecimalField(blank=True, decimal_places=6, help_text='Modified or approximate duration if provided by the source.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('source', models.CharField(default='static_provider', max_length=100)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('ai_summary', models.TextField(blank=True, help_text='Optional future AI-generated summary based only on validated data.')),
                ('ai_reasoning', models.TextField(blank=True, help_text='Optional future AI-generated reasoning based only on validated data.')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('ADDED_TO_WATCHLIST', 'Added to Watchlist'), ('IGNORED', 'Ignored')], db_index=True, default='NEW', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_candidates', to=settings.AUTH_USER_MODEL)),
                ('discovery_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='bonds.discoveryrun')),
            ],
            options={
                'verbose_name': 'Bond Candidate',
                'verbose_name_plural': 'Bond Candidates',
                'ordering': ['maturity_date', 'isin'],
                'constraints': [models.UniqueConstraint(fields=('user', 'isin'), name='unique_bond_candidate_per_user_isin')],
            },
        ),
    ]
