# Generated by Django 6.0.6 on 2026-06-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_discoveryrun_bondcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondcandidate',
            name='confidence',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], db_index=True, default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='bondcandidate',
            name='data_origin',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('CSV_IMPORT', 'CSV Import'), ('STATIC_PROVIDER', 'Static Provider'), ('AI_RESEARCH', 'AI Research'), ('EXTERNAL_JSON', 'External JSON'), ('OTHER', 'Other')], db_index=True, default='STATIC_PROVIDER', max_length=30),
        ),
        migrations.AddField(
            model_name='bondcandidate',
            name='missing_fields',
            field=models.JSONField(blank=True, default=list, help_text='Fields missing from the researched/imported candidate.'),
        ),
        migrations.AddField(
            model_name='bondcandidate',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='bondcandidate',
            name='research_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Raw structured payload used to create this candidate.'),
        ),
        migrations.AddField(
            model_name='bondcandidate',
            name='retrieved_at',
            field=models.DateTimeField(blank=True, help_text='When this candidate was retrieved from the source.', null=True),
        ),
        migrations.AddField(
            model_name='bondcandidate',
            name='review_status',
            field=models.CharField(choices=[('NEEDS_REVIEW', 'Needs Review'), ('REVIEWED', 'Reviewed'), ('REJECTED', 'Rejected')], db_index=True, default='NEEDS_REVIEW', max_length=30),
        ),
        migrations.AddField(
            model_name='bondmarketdata',
            name='confidence',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], db_index=True, default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='bondmarketdata',
            name='data_origin',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('CSV_IMPORT', 'CSV Import'), ('STATIC_PROVIDER', 'Static Provider'), ('AI_RESEARCH', 'AI Research'), ('EXTERNAL_JSON', 'External JSON'), ('OTHER', 'Other')], db_index=True, default='MANUAL', max_length=30),
        ),
        migrations.AddField(
            model_name='bondmarketdata',
            name='missing_fields',
            field=models.JSONField(blank=True, default=list, help_text='Fields that were missing during import or AI research.'),
        ),
        migrations.AddField(
            model_name='bondmarketdata',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bondmarketdata',
            name='research_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Raw structured payload used to create this record.'),
        ),
        migrations.AddField(
            model_name='bondmarketdata',
            name='retrieved_at',
            field=models.DateTimeField(blank=True, help_text='When this record was retrieved from the source.', null=True),
        ),
        migrations.AddField(
            model_name='bondmarketdata',
            name='review_status',
            field=models.CharField(choices=[('NEEDS_REVIEW', 'Needs Review'), ('REVIEWED', 'Reviewed'), ('REJECTED', 'Rejected')], db_index=True, default='REVIEWED', max_length=30),
        ),
        migrations.AddField(
            model_name='bondmarketdata',
            name='source_url',
            field=models.URLField(blank=True, help_text='Source URL used for this market data record, when available.', max_length=500),
        ),
    ]
