# Generated by Django 6.0.6 on 2026-06-18 19:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bonds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_type', models.CharField(choices=[('PORTFOLIO', 'Portfolio'), ('WATCHLIST', 'Watchlist')], default='WATCHLIST', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Number of bonds owned. Usually 0 for Watchlist items.')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=4, help_text='Purchase price per bond, if the bond is in Portfolio.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('base_currency', models.CharField(default='EUR', help_text='Investor base currency, for example EUR or USD.', max_length=3)),
                ('reinvest_coupons', models.BooleanField(default=False, help_text='Used for reinvested coupon yield calculations.')),
                ('trading_fees_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Trading fees as percentage.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('100.0000'))])),
                ('coupon_tax_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Coupon tax as percentage.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('100.0000'))])),
                ('expected_yield_change', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), help_text='Expected yield change Δy as percentage.', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-100.00000')), django.core.validators.MaxValueValidator(Decimal('100.00000'))])),
                ('valuation_threshold_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Threshold used to decide if IV is materially above/below MP.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('100.0000'))])),
                ('evaluation_basis', models.CharField(choices=[('MARKET_DATA', 'Market Data'), ('PERSONAL_TARGET', 'Personal Target'), ('CONSERVATIVE', 'Conservative'), ('BALANCED', 'Balanced')], default='MARKET_DATA', max_length=30)),
                ('target_required_return', models.DecimalField(blank=True, decimal_places=5, help_text='Optional personal return target. This is not the main market discount rate used for valuation.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-100.00000')), django.core.validators.MaxValueValidator(Decimal('100.00000'))])),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_positions', to='bonds.bond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bonds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Bond',
                'verbose_name_plural': 'User Bonds',
                'ordering': ['user', 'holding_type', 'bond__isin'],
                'unique_together': {('user', 'bond', 'holding_type')},
            },
        ),
    ]
